### ISSUE TITLE
Could you please specify the browser support in README

### ISSUE THREAD

**Issue by Srikanth-AD** [wmartins/react-circular-progress#6]

**Comment by wmartins** [comment]
Hi @modestkdr, I'll do that soon.

I tested that in Chrome, Firefox and IE11, but I think IE10 is also supported.

Due to possible SVG issues, I don't know if it will work on IE9 and even IE8, but I will check it out! :)

It this enough by now?

**Comment by Srikanth-AD** [comment]
Browser support for SVG: http://caniuse.com/#search=svg
Yes, thank you.
